#ifndef INCG_PHI_UNITTEST_CONSTEXPRHELPER_HPP
#define INCG_PHI_UNITTEST_CONSTEXPRHELPER_HPP

#if defined(CATCH_CONFIG_RUNTIME_STATIC_REQUIRE)
#    define CONSTEXPR_RUNTIME /* Nothing */
#else
#    define CONSTEXPR_RUNTIME constexpr
#endif

#endif // INCG_PHI_UNITTEST_CONSTEXPRHELPER_HPP
