phi_include_guard()

include(internal/PhiAddExecutables)
include(internal/PhiAddLibrary)
include(internal/PhiCheckCompilerFlag)
include(internal/PhiCheckCompilerFlagCommonPatterns)
include(internal/PhiCheckCXXCompilerFlag)
include(internal/PhiCheckCXXSourceCompiles)
include(internal/PhiError)
include(internal/PhiGetAllTargets)
include(internal/PhiLog)
include(internal/PhiMessage)
include(internal/PhiOption)
include(internal/PhiSetCacheValue)
include(internal/PhiTrace)
include(internal/PhiWarn)
include(internal/TargetCompileFeatures)
include(internal/TargetLinkOptions)
