#ifndef INCG_PHI_CORE_COMPILER_SUPPORT_EXTENSIONS_PRAGMA_ONCE_HPP
#define INCG_PHI_CORE_COMPILER_SUPPORT_EXTENSIONS_PRAGMA_ONCE_HPP

#include "phi/compiler_support/compiler.hpp"

#if PHI_COMPILER_IS(GCC) || PHI_COMPILER_IS(CLANG_COMPAT) || PHI_COMPILER_IS(MSVC) ||              \
        PHI_COMPILER_IS(ICC)
#    define PHI_HAS_EXTENSION_PRAGMA_ONCE() 1

#    pragma once

#else
#    define PHI_HAS_EXTENSION_PRAGMA_ONCE() 0
#endif

#endif // INCG_PHI_CORE_COMPILER_SUPPORT_EXTENSIONS_PRAGMA_ONCE_HPP
