#!/bin/bash

export PROC_COUNT=$(nproc)

# Setup CMake stuff
echo "CMAKE_BUILD_PARALLEL_LEVEL=${PROC_COUNT}" >>$GITHUB_ENV
echo "CTEST_PARALLEL_LEVEL=${PROC_COUNT}" >>$GITHUB_ENV
echo "CTEST_OUTPUT_ON_FAILURE=ON" >>$GITHUB_ENV
echo "CMAKE_DEFAULT_CONFIGURE_OPTIONS=-DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON" >>$GITHUB_ENV
