#!/bin/bash

# Get number of processors available
echo "PROC_COUNT=$(nproc)" >>$GITHUB_ENV
echo "OS_CODENAME=$(lsb_release -c -s)" >> $GITHUB_ENV

# Setup CMake stuff
echo "CMAKE_BUILD_PARALLEL_LEVEL=${PROC_COUNT}" >>$GITHUB_ENV
echo "CTEST_PARALLEL_LEVEL=${PROC_COUNT}" >>$GITHUB_ENV
echo "CTEST_OUTPUT_ON_FAILURE=ON" >>$GITHUB_ENV
echo "CMAKE_DEFAULT_CONFIGURE_OPTIONS=-DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON" >>$GITHUB_ENV

# Latest versions
echo "LATEST_LLVM_VERSION=14" >>$GITHUB_ENV
echo "LATEST_GCC_VERSION=11" >>$GITHUB_ENV
