#include <phi/test/test_macros.hpp>

#include <phi/preprocessor/bool.hpp>

TEST_CASE("PHI_BOOL")
{
    STATIC_REQUIRE_FALSE(PHI_BOOL(0));
    STATIC_REQUIRE(PHI_BOOL(1));
    STATIC_REQUIRE(PHI_BOOL(2));
    STATIC_REQUIRE(PHI_BOOL(3));
    STATIC_REQUIRE(PHI_BOOL(4));
    STATIC_REQUIRE(PHI_BOOL(5));
    STATIC_REQUIRE(PHI_BOOL(6));
    STATIC_REQUIRE(PHI_BOOL(7));
    STATIC_REQUIRE(PHI_BOOL(8));
    STATIC_REQUIRE(PHI_BOOL(9));
    STATIC_REQUIRE(PHI_BOOL(10));
}
