#ifndef INCH_PHI_CORE_COMPILER_SUPPORT_INTRINSICS_HAS_TRIVIAL_DESTRUCTOR_HPP
#define INCH_PHI_CORE_COMPILER_SUPPORT_INTRINSICS_HAS_TRIVIAL_DESTRUCTOR_HPP

#include "Phi/PhiConfig.hpp"

#if PHI_HAS_EXTENSION_PRAGMA_ONCE()
#    pragma once
#endif

#include "Phi/CompilerSupport/Features.hpp"

#if PHI_HAS_INTRINSIC_HAS_TRIVIAL_DESTRUCTOR()
#    define PHI_HAS_TRIVIAL_DESTRUCTOR(type)      __has_trivial_destructor(type)
#    define PHI_SUPPORTS_HAS_TRIVIAL_DESTRUCTOR() 1
#else
#    define PHI_HAS_TRIVIAL_DESTRUCTOR(type)      false
#    define PHI_SUPPORTS_HAS_TRIVIAL_DESTRUCTOR() 0
#endif

#if defined(PHI_CONFIG_NO_INTRINSICS)
#    undef PHI_SUPPORTS_HAS_TRIVIAL_DESTRUCTOR
#    define PHI_SUPPORTS_HAS_TRIVIAL_DESTRUCTOR() 0
#endif

#endif // INCH_PHI_CORE_COMPILER_SUPPORT_INTRINSICS_HAS_TRIVIAL_DESTRUCTOR_HPP
