#ifndef INCH_PHI_CORE_COMPILER_SUPPORT_INTRINSICS_IS_FLOATING_POINT_HPP
#define INCH_PHI_CORE_COMPILER_SUPPORT_INTRINSICS_IS_FLOATING_POINT_HPP

#include "Phi/PhiConfig.hpp"

#if PHI_HAS_EXTENSION_PRAGMA_ONCE()
#    pragma once
#endif

#include "Phi/CompilerSupport/Features.hpp"

#if PHI_HAS_INTRINSIC_IS_FLOATING_POINT()
#    define PHI_IS_FLOATING_POINT(type)      __is_floating_point(type)
#    define PHI_SUPPORTS_IS_FLOATING_POINT() 1
#else
#    define PHI_IS_FLOATING_POINT(type)      false
#    define PHI_SUPPORTS_IS_FLOATING_POINT() 0
#endif

#if defined(PHI_CONFIG_NO_INTRINSICS)
#    undef PHI_SUPPORTS_IS_FLOATING_POINT
#    define PHI_SUPPORTS_IS_FLOATING_POINT() 0
#endif

#endif // INCH_PHI_CORE_COMPILER_SUPPORT_INTRINSICS_IS_FLOATING_POINT_HPP
