#ifndef INCH_PHI_CORE_COMPILER_SUPPORT_INTRINSICS_IS_FUNDAMENTAL_HPP
#define INCH_PHI_CORE_COMPILER_SUPPORT_INTRINSICS_IS_FUNDAMENTAL_HPP

#include "Phi/PhiConfig.hpp"

#if PHI_HAS_EXTENSION_PRAGMA_ONCE()
#    pragma once
#endif

#include "Phi/CompilerSupport/Features.hpp"

#if PHI_HAS_INTRINSIC_IS_FUNDAMENTAL()
#    define PHI_IS_FUNDAMENTAL(type)      __is_fundamental(type)
#    define PHI_SUPPORTS_IS_FUNDAMENTAL() 1
#else
#    define PHI_IS_FUNDAMENTAL(type)      false
#    define PHI_SUPPORTS_IS_FUNDAMENTAL() 0
#endif

#if defined(PHI_CONFIG_NO_INTRINSICS)
#    undef PHI_SUPPORTS_IS_FUNDAMENTAL
#    define PHI_SUPPORTS_IS_FUNDAMENTAL() 0
#endif

#endif // INCH_PHI_CORE_COMPILER_SUPPORT_INTRINSICS_IS_FUNDAMENTAL_HPP
