#ifndef INCH_PHI_CORE_COMPILER_SUPPORT_INTRINSICS_IS_TRIVIALLY_DESTRUCTIBLE_HPP
#define INCH_PHI_CORE_COMPILER_SUPPORT_INTRINSICS_IS_TRIVIALLY_DESTRUCTIBLE_HPP

#include "Phi/PhiConfig.hpp"

#if PHI_HAS_EXTENSION_PRAGMA_ONCE()
#    pragma once
#endif

#include "Phi/CompilerSupport/Features.hpp"

#if PHI_HAS_INTRINSIC_IS_TRIVIALLY_DESTRUCTIBLE()
#    define PHI_IS_TRIVIALLY_DESTRUCTIBLE(type)      __is_trivially_destructible(type)
#    define PHI_SUPPORTS_IS_TRIVIALLY_DESTRUCTIBLE() 1
#elif PHI_HAS_INTRINSIC_HAS_TRIVIAL_DESTRUCTOR() && PHI_COMPILER_IS(MSVC)
#    define PHI_IS_TRIVIALLY_DESTRUCTIBLE(type)      __has_trivial_destructor(type)
#    define PHI_SUPPORTS_IS_TRIVIALLY_DESTRUCTIBLE() 1
#else
#    define PHI_IS_TRIVIALLY_DESTRUCTIBLE(type)      false
#    define PHI_SUPPORTS_IS_TRIVIALLY_DESTRUCTIBLE() 0
#endif

#if defined(PHI_CONFIG_NO_INTRINSICS)
#    undef PHI_SUPPORTS_IS_TRIVIALLY_DESTRUCTIBLE
#    define PHI_SUPPORTS_IS_TRIVIALLY_DESTRUCTIBLE() 0
#endif

#endif // INCH_PHI_CORE_COMPILER_SUPPORT_INTRINSICS_IS_TRIVIALLY_DESTRUCTIBLE_HPP
