name: Archive

on:
  push:
    paths:
      # Workflow file itself
      - '.github/workflows/Archive.yml'
      # Script file
      - 'scripts/ci/ArchiveAllLinks.sh'
  schedule:
    - cron: '0 4 1 * *' # At 04:00 on the first day of the month
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  links:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run Script
        run: scripts/ci/ArchiveAllLinks.sh
