name: Archive

on:
  schedule:
    - cron: '0 4 1 * *' # At 04:00 on the first day of the month
  workflow_dispatch:

links:
  linux:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run Script
        run: scripts/ci/archive_all_links.sh
