name: ClusterFuzzLite continuous builds

# https://google.github.io/clusterfuzzlite/running-clusterfuzzlite/github-actions/

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  release:
    types: [published]
  workflow_dispatch:

permissions: read-all

jobs:
  Build:
    runs-on: ubuntu-22.04

    # Don't run on dependabot PRs
    if: github.actor != 'dependabot[bot]'

    concurrency:
      group: ${{ github.workflow }}-${{ matrix.sanitizer }}-${{ github.ref }}
      cancel-in-progress: true

    strategy:
      fail-fast: false

      matrix:
        sanitizer:
          - address
          - memory
          - undefined

    steps:
      - name: Build Fuzzers (${{ matrix.sanitizer }})
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: c++ # Change this to the language you are fuzzing.
          sanitizer: ${{ matrix.sanitizer }}
          upload-build: true
