name: ClusterFuzzLite continuous builds

# https://google.github.io/clusterfuzzlite/running-clusterfuzzlite/github-actions/

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions: read-all

jobs:
  Build:
    # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md
    runs-on: ubuntu-20.04

    concurrency:
      group: ${{ github.workflow }}-${{ matrix.sanitizer }}-${{ github.ref }}
      cancel-in-progress: true

    strategy:
      fail-fast: false

      matrix:
        sanitizer:
          - address
          - memory
          - undefined

    steps:
      - name: Build Fuzzers (${{ matrix.sanitizer }})
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: c++ # Change this to the language you are fuzzing.
          sanitizer: ${{ matrix.sanitizer }}
          upload-build: true
