name: ClusterFuzzLite batch fuzzing

# https://google.github.io/clusterfuzzlite/running-clusterfuzzlite/github-actions/

on:
  schedule:
    - cron: '0 0/6 * * *'  # Every 6th hour. Change this to whatever is suitable.
  push:
    branches:
      - main
      - develop
  release:
    types: [published]
  workflow_dispatch:

permissions: read-all

jobs:
  BatchFuzzing:
    # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false

      matrix:
        sanitizer:
          - address
          - memory
          - undefined

    steps:
    - name: Build Fuzzers (${{ matrix.sanitizer }})
      id: build
      uses: google/clusterfuzzlite/actions/build_fuzzers@v1
      with:
        language: c++ # Change this to the language you are fuzzing.
        sanitizer: ${{ matrix.sanitizer }}

    - name: Run Fuzzers (${{ matrix.sanitizer }})
      id: run
      uses: google/clusterfuzzlite/actions/run_fuzzers@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        fuzz-seconds: 10800 # 3 Hours
        mode: 'batch'
        sanitizer: ${{ matrix.sanitizer }}
        # Optional but recommended: For storing certain artifacts from fuzzing.
        # See later section on "Git repo for storage".
        storage-repo: https://${{ secrets.CORPUS_PAT }}@github.com/AMS21/phi-corpus.git
        storage-repo-branch: main   # Optional. Defaults to "main"
        storage-repo-branch-coverage: gh-pages  # Optional. Defaults to "gh-pages".
