name: CMake

on:
  push:
    paths:
      # Workflow file itself
      - '.github/workflows/CMake.yml'
      # CMake files
      - '**.cmake'
      - '**.txt'
      # Script files
      - '**.sh'
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  configure:
    runs-on: 'ubuntu-22.04'
    container: 'ams21/cmake:${{ matrix.version }}'

    strategy:
      fail-fast: false

      matrix:
        version:
          # CMake 3.29.x
          - "v3.29.0"

          # CMake 3.28.x
          - "v3.28.4"
          - "v3.28.3"
          - "v3.28.2"
          - "v3.28.1"
          - "v3.28.0"

          # CMake 3.27.x
          - "v3.27.9"
          - "v3.27.8"
          - "v3.27.7"
          - "v3.27.6"
          - "v3.27.5"
          - "v3.27.4"
          - "v3.27.3"
          - "v3.27.2"
          - "v3.27.1"
          - "v3.27.0"

          # CMake 3.26.x
          - "v3.26.6"
          - "v3.26.5"
          - "v3.26.4"
          - "v3.26.3"
          - "v3.26.2"
          - "v3.26.1"
          - "v3.26.0"

          # CMake 3.25.x
          - "v3.25.3"
          - "v3.25.2"
          - "v3.25.1"
          - "v3.25.0"

          # CMake 3.24.x
          - "v3.24.4"
          - "v3.24.3"
          - "v3.24.2"
          - "v3.24.1"
          - "v3.24.0"

          # CMake 3.23.x
          - "v3.23.5"
          - "v3.23.4"
          - "v3.23.3"
          - "v3.23.2"
          - "v3.23.1"
          - "v3.23.0"

          # CMake 3.22.x
          - "v3.22.6"
          - "v3.22.5"
          - "v3.22.4"
          - "v3.22.3"
          - "v3.22.2"
          - "v3.22.1"
          - "v3.22.0"

          # CMake 3.21.x
          - "v3.21.7"
          - "v3.21.6"
          - "v3.21.5"
          - "v3.21.4"
          - "v3.21.3"
          - "v3.21.2"
          - "v3.21.1"
          - "v3.21.0"

          # CMake 3.20.x
          - "v3.20.6"
          - "v3.20.5"
          - "v3.20.4"
          - "v3.20.3"
          - "v3.20.2"
          - "v3.20.1"
          - "v3.20.0"

          # CMake 3.19.x
          - "v3.19.8"
          - "v3.19.7"
          - "v3.19.6"
          - "v3.19.5"
          - "v3.19.4"
          - "v3.19.3"
          - "v3.19.2"
          - "v3.19.1"
          - "v3.19.0"

          # CMake 3.18.x
          - "v3.18.6"
          - "v3.18.5"
          - "v3.18.4"
          - "v3.18.3"
          - "v3.18.2"
          - "v3.18.1"
          - "v3.18.0"

          # CMake 3.17.x
          - "v3.17.5"
          - "v3.17.4"
          - "v3.17.3"
          - "v3.17.2"
          - "v3.17.1"
          - "v3.17.0"

          # CMake 3.16.x
          - "v3.16.9"
          - "v3.16.8"
          - "v3.16.7"
          - "v3.16.6"
          - "v3.16.5"
          - "v3.16.4"
          - "v3.16.3"
          - "v3.16.2"
          - "v3.16.1"
          - "v3.16.0"

          # CMake 3.15.x
          - "v3.15.7"
          - "v3.15.6"
          - "v3.15.5"
          - "v3.15.4"
          - "v3.15.3"
          - "v3.15.2"
          - "v3.15.1"
          - "v3.15.0"

          # CMake 3.14.x
          - "v3.14.7"
          - "v3.14.6"
          - "v3.14.5"
          - "v3.14.4"
          - "v3.14.3"
          - "v3.14.2"
          - "v3.14.1"
          - "v3.14.0"

          # CMake 3.13.x
          - "v3.13.5"
          - "v3.13.4"
          - "v3.13.3"
          - "v3.13.2"
          - "v3.13.1"
          - "v3.13.0"

          # CMake 3.12.x
          - "v3.12.4"
          - "v3.12.3"
          - "v3.12.2"
          - "v3.12.1"
          - "v3.12.0"

          # CMake 3.11.x
          - "v3.11.4"
          - "v3.11.3"
          - "v3.11.2"
          - "v3.11.1"
          - "v3.11.0"

          # CMake 3.10.x
          - "v3.10.3"
          - "v3.10.2"
          - "v3.10.1"
          - "v3.10.0"

          # CMake 3.9.x
          - "v3.9.6"
          - "v3.9.5"
          - "v3.9.4"
          - "v3.9.3"
          - "v3.9.2"
          - "v3.9.1"
          - "v3.9.0"

          # CMake 3.8.x
          - "v3.8.2"
          - "v3.8.1"
          - "v3.8.0"

          # CMake 3.7.x
          - "v3.7.2"
          - "v3.7.1"
          - "v3.7.0"

          # CMake 3.6.x
          - "v3.6.3"
          - "v3.6.2"
          - "v3.6.1"
          - "v3.6.0"

          # CMake 3.5.x
          - "v3.5.2"
          - "v3.5.1"
          - "v3.5.0"

          # CMake 3.4.x
          - "v3.4.3"
          - "v3.4.2"
          - "v3.4.1"
          - "v3.4.0"

          # CMake 3.3.x
          - "v3.3.2"
          - "v3.3.1"
          - "v3.3.0"

          # CMake 3.2.x
          - "v3.2.3"
          - "v3.2.2"
          - "v3.2.1"
          - "v3.2.0"

          # CMake 3.1.x
          - "v3.1.3"
          - "v3.1.2"
          - "v3.1.1"
          - "v3.1.0"

          # CMake 3.0.x
          - "v3.0.2"
          - "v3.0.1"
          - "v3.0.0"

          # CMake 2.8.x
          - "v2.8.12"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure build directory
        run: |
          mkdir build -p
          cd build

          cmake ..
