name: CMake

on:
  push:
    paths:
      # Workflow file itself
      - '.github/workflows/CMake.yml'
      # CMake files
      - '**.cmake'
      - '**.txt'
      # Script files
      - '**.sh'
  pull_request:
    branches:
      - main
      - develop
    paths:
      # Workflow file itself
      - '.github/workflows/CMake.yml'
      # CMake files
      - '**.cmake'
      - '**.txt'
      # Script files
      - '**.sh'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  configure:
    runs-on: 'ubuntu-22.04'
    container: 'ams21/cmake:${{ matrix.version }}'

    # Don't run on dependabot PRs
    if: github.actor != 'dependabot[bot]'

    strategy:
      fail-fast: false

      matrix:
        version:
          - "3.30"
          - "3.29"
          - "3.28"
          - "3.27"
          - "3.26"
          - "3.25"
          - "3.24"
          - "3.23"
          - "3.22"
          - "3.21"
          - "3.20"
          - "3.19"
          - "3.18"
          - "3.17"
          - "3.16"
          - "3.15"
          - "3.14"
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"
          - "3.7"
          - "3.6"
          - "3.5"
          - "3.4"
          - "3.3"
          - "3.2"
          - "3.1"
          - "3.0"
          - "2.8"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure build directory
        run: |
          mkdir build -p
          cd build

          cmake ..
