name: CoverityScan

on:
  schedule:
    - cron: '0 4 * * 1' # Every monday at 4:00 UTC
  push:
    branches:
      - 'coverity/**'

jobs:
  trunk:
    runs-on: ubuntu-latest

    env:
      GCC_VERSION: "8"

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: 'develop'
          submodules: recursive

      - name: Install cmake
        uses: lukka/get-cmake@3.19.1

      - name: Install
        run: |
          # Update repo list
          sudo apt-get update -m

          # Install g++
          sudo apt-get install "g++-${{ env.GCC_VERSION }}" "g++-${{ env.GCC_VERSION }}-multilib" -y

          # export compiler
          echo "CXX=g++-${{ env.GCC_VERSION }}" >> $GITHUB_ENV

      - name: Download Coverity Build Tool
        run: |
          wget -q https://scan.coverity.com/download/cxx/linux64 --post-data "token=$TOKEN&project=AMS21%2FPhi" -O cov-analysis-linux64.tar.gz
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Configure cov-build
        run: |
          export PATH=`pwd`/cov-analysis-linux64/bin:$PATH

          cov-configure --comptype gcc --compiler /usr/bin/g++-${{ env.GCC_VERSION }} -- -std=gnu++2a

      - name: Build with cov-build
        env:
          COVERITY_UNSUPPORTED_COMPILER_INVOCATION: 1
        run: |
          export PATH=`pwd`/cov-analysis-linux64/bin:$PATH

          cd build
          cov-build --dir cov-int make

      - name: Print build log
        run: |
          cat build/cov-int/build-log.txt

      - name: Submit the result to Coverity Scan
        run: |
          cd build
          tar czvf phi.tgz cov-int
          curl --form token=$TOKEN \
               --form email=hansfritzenmeister@protonmail.com \
               --form file=@phi.tgz \
               --form version="trunk" \
               --form description="Automatic submission" \
               https://scan.coverity.com/builds?project=AMS21%2FPhi
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
