name: Emscripten

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-20.04

    env:
      CMAKE_BUILD_PARALLEL_LEVEL: "2"
      CTEST_PARALLEL_LEVEL: "2"
      CTEST_OUTPUT_ON_FAILURE: "ON"
      EM_CACHE_FOLDER: 'emsdk-cache'

    strategy:
      fail-fast: false
      matrix:
        em_version: ["2.0.24", "2.0.23", "2.0.22", "2.0.21", "2.0.18", "2.0.17", "2.0.16", "2.0.15", "2.0.14", "2.0.13", "2.0.12", "1.40.1"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          submodules: recursive

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v10
        with:
          version: ${{ matrix.em_version }}
          actions-cache-folder: ${{ env.EM_CACHE_FOLDER }}

      - name: Verify version
        run: |
          emcc --version

      - name: Install cmake
        uses: lukka/get-cmake@v3.21.1

      - name: Configure build directory
        run: |
          mkdir -p build
          cd build
          emcmake cmake -DCMAKE_VERBOSE_MAKEFILE=ON ..

      - name: Build Debug
        run: |
          cd build
          emcmake cmake .. -DCMAKE_BUILD_TYPE=Debug
          emmake cmake --build . --clean-first
          ctest . -C Debug

      - name: Build RelWithDebInfo
        run: |
          cd build
          emcmake cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo
          emmake cmake --build . --clean-first
          ctest . -C RelWithDebInfo

      - name: Build Release
        run: |
          cd build
          emcmake cmake .. -DCMAKE_BUILD_TYPE=Release
          emmake cmake --build . --clean-first
          ctest . -C Release

  Warnings:
    runs-on: ubuntu-20.04

    env:
      CMAKE_BUILD_PARALLEL_LEVEL: "2"
      EM_CACHE_FOLDER: 'emsdk-cache'
      EM_VERSION: '2.0.24'

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          submodules: recursive

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v10
        with:
          version: ${{ env.EM_VERSION }}
          actions-cache-folder: ${{ env.EM_CACHE_FOLDER }}

      - uses: reviewdog/action-setup@v1.0.3
        with:
          reviewdog_version: latest

      - name: Install cmake
        uses: lukka/get-cmake@v3.21.1

      - name: Generate warnings
        run: |
          # Build
          mkdir build
          cd build
          
          emcmake cmake .. -DCMAKE_BUILD_TYPE=Debug
          emmake cmake --build . --clean-first 2> build.log

          # Filter out warnings for external dependencies
          cat build.log | grep -Ev "Phi/external" > build_filtered.log || true

      - name: Print results
        run: cat build/build_filtered.log

      - name: ReviewDog check
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat build/build_filtered.log | reviewdog -efm="%f:%l:%c: warning: %m" -diff="git diff HEAD~1" -reporter=github-check -name "Emscripten-${{ env.EM_VERSION }} warnings" -level warning
