name: Emscripten

on:
  push:
    paths:
      # Workflow file itself
      - '.github/workflows/Emscripten.yml'
      # C++ files
      - '**.cpp'
      - '**.hpp'
      # CMake files
      - '**.cmake'
      - '**.txt'
      # Script files
      - '**.sh'
    tags:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches:
      - main
      - develop
  release:
    types: [published]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-20.04

    env:
      EM_CACHE_FOLDER: 'emsdk-cache'

    strategy:
      fail-fast: false

      matrix:
        em_version:
          - "3.1.9"
          - "3.0.1"
          - "2.0.34"
          - "1.40.1"
          - "1.39.20"
          - "1.38.48"

        build_type:
          - "Debug"
          - "RelWithDebInfo"
          - "Release"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.os }}-emscripten-${{ matrix.em_version }}-${{ matrix.build_type }}

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{ matrix.em_version }}
          actions-cache-folder: ${{ env.EM_CACHE_FOLDER }}

      - name: Verify version
        run: |
          emcc --version

      - name: Setup Environment
        run: scripts/ci/SetupEnvironment.sh

      - name: Install nija
        run: scripts/ci/InstallTools.sh ninja

      - name: Configure build directory
        run: |
          mkdir -p build
          cd build

          emcmake cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_VERBOSE_MAKEFILE=ON ..

      - name: Build
        working-directory: build
        run: emmake cmake --build .

      - name: Run tests
        working-directory: build
        run: ctest . -C ${{ matrix.build_type }}
