name: Emscripten

on:
  push:
    paths:
      # Workflow file itself
      - '.github/workflows/Emscripten.yml'
      # C++ files
      - '**.cpp'
      - '**.hpp'
      # CMake files
      - '**.cmake'
      - '**.txt'
      # Script files
      - '**.sh'
    tags:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches:
      - main
      - develop
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false

      matrix:
        em_version:
          - "3.1.55"
          - "3.1.54"
          - "3.1.53"
          - "3.1.52"
          - "3.1.51"
          - "3.1.50"
          - "3.1.49"
          - "3.1.48"
          - "3.1.47"
          - "3.1.46"
          - "3.1.45"
          - "3.1.44"
          - "3.1.43"
          - "3.1.42"
          - "3.1.41"
          - "3.1.40"
          - "3.1.39"
          - "3.1.38"
          - "3.1.37"
          - "3.1.36"
          - "3.1.35"
          - "3.1.34"
          - "3.1.33"
          - "3.1.32"
          - "3.1.31"
          - "3.1.30"
          - "3.1.29"
          - "3.1.28"
          - "3.1.27"
          - "3.1.26"
          - "3.1.25"
          - "3.1.24"
          - "3.1.23"
          - "3.1.22"
          - "3.1.21"
          - "3.1.20"
          - "3.1.19"
          - "3.1.18"
          - "3.1.17"
          - "3.1.16"
          - "3.1.15"
          - "3.1.14"
          - "3.1.13"
          - "3.1.12"
          - "3.1.11"
          - "3.1.10"
          - "3.1.9"
          - "3.1.8"
          - "3.1.7"
          - "3.1.6"
          - "3.1.5"
          - "3.1.4"
          - "3.1.3"
          - "3.1.2"
          - "3.1.1"
          - "3.1.0"
          - "3.0.1"
          - "3.0.0"
          - "2.0.34"
          - "2.0.33"
          - "2.0.32"
          - "2.0.31"
          - "2.0.30"
          - "2.0.29"
          - "2.0.28"
          - "2.0.27"
          - "2.0.26"
          - "2.0.25"
          - "2.0.24"
          - "2.0.23"
          - "2.0.22"
          - "2.0.21"
          - "2.0.20"
          - "2.0.19"
          - "2.0.18"
          - "2.0.17"
          - "2.0.16"
          - "2.0.15"
          - "2.0.14"
          - "2.0.13"
          - "2.0.12"
          - "2.0.11"
          - "2.0.10"
          - "2.0.9"
          - "2.0.8"
          - "2.0.7"
          - "2.0.6"
          - "2.0.5"
          - "2.0.4"
          - "2.0.3"
          - "2.0.2"
          - "2.0.1"
          - "2.0.0"
          - "1.40.1"

        build_type:
          - "Debug"
          - "Release"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        # Continue on error to ignore problems with caching
        continue-on-error: true
        with:
          version: ${{ matrix.em_version }}
          no-cache: true

      - name: Verify version
        run: emcc --version

      - name: Setup Environment
        run: scripts/ci/SetupEnvironment.sh

      - name: Install ninja
        run: scripts/ci/InstallTools.sh ninja

      - name: Configure build directory
        run: |
          mkdir -p build
          cd build

          emcmake cmake -DCMAKE_BUILD_TYPE:STRING=${{ matrix.build_type }} -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON ..

      - name: Build
        working-directory: ./build
        run: emmake cmake --build . --config ${{ matrix.build_type }}

      - name: Run tests
        working-directory: ./build
        run: ctest . -C ${{ matrix.build_type }}
