name: Emscripten

on:
  push:
    paths:
      # Workflow file itself
      - '.github/workflows/Emscripten.yml'
      # C++ files
      - '**.cpp'
      - '**.hpp'
      # CMake files
      - '**.cmake'
      - '**.txt'
      # Script files
      - '**.sh'
    tags:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches:
      - main
      - develop
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false

      matrix:
        em_version:
          - "3.1.29"
          - "3.0.1"
          - "2.0.34"
          - "1.40.1"
          - "1.39.20"

        build_type:
          - "Debug"
          - "RelWithDebInfo"
          - "Release"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v12
        # Continue on error to ignore problems with caching
        continue-on-error: true
        with:
          version: ${{ matrix.em_version }}
          no-cache: true

      - name: Verify version
        run: emcc --version

      - name: Setup Environment
        run: scripts/ci/SetupEnvironment.sh

      - name: Install ninja
        run: scripts/ci/InstallTools.sh ninja

      - name: Configure build directory
        run: |
          mkdir -p build
          cd build

          emcmake cmake -DCMAKE_BUILD_TYPE:STRING=${{ matrix.build_type }} -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON ..

      - name: Build
        working-directory: ./build
        run: emmake cmake --build . --config ${{ matrix.build_type }}

      - name: Run tests
        working-directory: ./build
        run: ctest . -C ${{ matrix.build_type }}
