name: Licensed

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check Licenses

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          submodules: recursive
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Install Licensed
        uses: jonabc/setup-licensed@v1.0.1
        with:
          version: '2.x'

      - name: Update licenses
        if: ${{ github.event_name == 'push' }}
        run: licensed cache

      - name: Import GPG key
        if: ${{ github.event_name == 'push' }}
        uses: crazy-max/ghaction-import-gpg@v2.2.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.BOT_KEY_PASSPHRASE }}
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Commit changes
        if: ${{ github.event_name == 'push' }}
        uses: stefanzweifel/git-auto-commit-action@v4.4.1
        continue-on-error: false
        with:
          commit_message: Auto-update license files
          branch: ${{ github.head_ref }}
          commit_options: '-S --no-verify --signoff'
          commit_user_name: Phi Code License Bot
          commit_user_email: AMS21Bot.github@gmail.com
          commit_author: AMS21Bot <AMS21Bot.github@gmail.com>
          file_pattern: .licenses/*

      - name: Check licenses
        run: licensed status
