name: Licensed

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check Licenses

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          submodules: recursive

      - name: Install Licensed
        uses: jonabc/setup-licensed@v1.0.1
        with:
          version: '2.x'

      - name: Check licenses
        if: ${{ github.event_name == 'pull_request' }}
        run : licensed status

      - name: Update licenses
        if: ${{ github.event_name == 'push' }}
        uses: jonabc/licensed-ci@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
