name: Linux-GCC

on:
  push:
    paths:
      # Workflow file itself
      - '.github/workflows/LinuxGCC.yml'
      # C++ files
      - '**.cpp'
      - '**.hpp'
      # CMake files
      - '**.cmake'
      - '**.txt'
      # Script files
      - '**.sh'
    tags:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches:
      - main
      - develop
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-20.04'

    strategy:
      fail-fast: false

      matrix:
        compiler_version:
          - "8"
          - "9"
          - "10"
          - "11"

        build_type:
          - "Debug"
          - "RelWithDebInfo"
          - "Release"

        dynamic_test:
          - "none"
          - "coverage"
          - "asan"
          - "lsan"
          - "tsan"
          - "ubsan"
          - "valgrind"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.os }}-gcc-${{ matrix.compiler_version }}-${{ matrix.build_type }}-${{ matrix.dynamic_test }}

      - name: Setup Environment
        run: scripts/ci/SetupEnvironment.sh

      - name: Install compiler
        run: scripts/ci/InstallTools.sh gcc-${{ matrix.compiler_version }}

      - name: Install gcovr
        if: matrix.dynamic_test == 'coverage'
        run: scripts/ci/InstallTools.sh gcovr

      - name: Install valgrind
        if: matrix.dynamic_test == 'valgrind'
        run: scripts/ci/InstallTools.sh valgrind

      - name: Configure build directory
        run: |
          mkdir build -p
          cd build

          # Export dynamic test mode
          echo "PHI_DYNAMIC_TEST=${{ matrix.dynamic_test }}" >> $GITHUB_ENV

          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..

      - name: Build
        working-directory: build
        run: cmake --build .

      - name: Run tests
        working-directory: build
        run: ctest . -C ${{ matrix.build_type }}

      - name: Process coverage data
        working-directory: build
        if: matrix.dynamic_test == coverage
        run: |
          gcovr -j $PROC_COUNT --delete --root ../ --print-summary --xml-pretty --xml coverage.xml . --gcov-executable '$GCOV_EXECUTABLE'

      - name: Upload coverage data
        if: matrix.dynamic_test == coverage
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./build/coverage.xml
          flags: ${{ runner.os }},gcc-${{ matrix.compiler_version }},${{ matrix.build_type }}
          name: ${{ runner.os }}-gcc-${{ matrix.compiler_version }}-${{ matrix.build_type }}
