name: PullRequestReview

on: pull_request

jobs:
  spelling:
    runs-on: ubuntu-latest

    steps:
      - name: Run misspell with reviewdog
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          # -locale flag of misspell. (US/UK)
          locale: US
          # Report level for reviewdog [info,warning,error]
          level: error
