name: Windows

on: [push, pull_request]

jobs:
  Build:
    name: "Build (${{ matrix.cfg.compiler }})"
    runs-on: windows-latest

    env:
      CTEST_OUTPUT_ON_FAILURE: ON
      CTEST_PARALLEL_LEVEL: 2

    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { compiler: cl, error_format: "%f(%l,%c): warning %m" }
          - { compiler: g++, error_format: "%f:%l:%c: warning: %m" }
          - { compiler: clang++, error_format: "%f:%l:%c: warning: %m" }
          - { compiler: clang-cl, error_format: "%f:%l:%c: warning: %m" }

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Install cmake
        uses: lukka/get-cmake@latest

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Install
        shell: powershell
        run: |
          # Install scoop
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')

          # Install required compilers
          if ("${{ matrix.cfg.compiler }}".StartsWith("clang")) {
            # Clang
            scoop install llvm --global
          }
          elseif ("${{ matrix.cfg.compiler }}" -eq "g++") {
            # GCC
            scoop install gcc --global
          }

          scoop install ninja --global

          echo "::set-env name=CXX::${{ matrix.cfg.compiler }}"
          # Scoop modifies the PATH so we make the modified PATH global.
          echo "::set-env name=PATH::$env:PATH"

      - name: Configure build directory
        run: |
          mkdir build
          cd build
          cmake .. -G Ninja

      - name: Build Debug
        run: |
          cd build
          cmake --build . --config "Debug" --clean-first
          ctest .

      - name: Build RelWithDebInfo
        run: |
          cd build
          cmake --build . --config "RelWithDebInfo" --clean-first
          ctest .

      - name: Build Release
        run: |
          cd build
          cmake --build . --config "Release" --clean-first
          ctest .

      - name: Generate warnings
        shell: bash
        run: |
          # Build
          cd build
          cmake --build . --config "Debug" --clean-first 2> build.log

          # Filter out warnings for external dependencies
          cat build.log | grep -Ev "Phi/external" > build_filtered.log || true

          # Print logs
          cat build_filtered.log

      - name: ReviewDog check
        shell: bash
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat build/build_filtered.log | reviewdog -efm="${{ matrix.cfg.error_format }}" -diff="git diff" -reporter=github-check -name "Windows ${{ matrix.cfg.compiler }} warnings" -level warning

      - name: ReviewDog Review
        shell: bash
        if: ${{ github.event_name == 'pull_request' }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat build/build_filtered.log | reviewdog -efm="${{ matrix.cfg.error_format }}" -diff="git diff" -reporter=github-pr-review -name "Windows ${{ matrix.cfg.compiler }} warnings" -level warning
